# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IMSPreparer
                                 A QGIS plugin
 This plugin prepares the IMS imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-14
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Leonid Kolesnichenko'
__date__ = '2024-02-14'
__copyright__ = '(C) 2024 by Leonid Kolesnichenko'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IMSPreparer class from file IMSPreparer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ims_preparer import IMSPreparerPlugin
    return IMSPreparerPlugin()
