# -*- coding: utf-8 -*-

"""
/***************************************************************************
 IMSPreparer
                                 A QGIS plugin
 This plugin prepares the IMS imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-14
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Leonid Kolesnichenko'
__date__ = '2024-02-14'
__copyright__ = '(C) 2024 by Leonid Kolesnichenko'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterString,
                       QgsProcessingParameterDateTime,
                       QgsProcessingParameterCrs,
                       QgsProcessingException,
                       QgsProcessingParameterDefinition)


class IMSPreparerAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT_LAYER = 'INPUT_LAYER'
    INPUT_BBOX = 'INPUT_BBOX'
    RASTER_DATE = "RASTER_DATE"
    OUTPUT_CRS = "OUTPUT_CRS"
    TYPE_CODES = "TYPE_CODES"
    TYPE_CODES_VALUES = "TYPE_CODES_VALUES"

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.

        input_layer_param = QgsProcessingParameterFeatureSource(
                self.INPUT_LAYER,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorPolygon]
            )

        input_layer_param.setFlags(input_layer_param.flags() | QgsProcessingParameterDefinition.FlagOptional)

        self.addParameter(
            input_layer_param
        )

        bbox_param = QgsProcessingParameterString(
                self.INPUT_BBOX,
                self.tr('Bounding box (with comma separated)'),
                defaultValue = ''
            )

        bbox_param.setFlags(bbox_param.flags() | QgsProcessingParameterDefinition.FlagOptional)

        self.addParameter(
            bbox_param
        )

        self.addParameter(
            QgsProcessingParameterDateTime(
                self.RASTER_DATE,
                self.tr('Raster date')
            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                self.OUTPUT_CRS,
                self.tr('Output CRS')
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.TYPE_CODES,
                self.tr('Type codes (comma separated)'),
                defaultValue=''
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.TYPE_CODES_VALUES,
                self.tr('Type codes values (comma separated)'),
                defaultValue=''
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source_layer = self.parameterAsSource(parameters, self.INPUT_LAYER, context)
        source_bbox = self.parameterAsString(parameters, self.INPUT_BBOX, context)
        type_codes = self.parameterAsString(parameters, self.TYPE_CODES, context).split(",")
        type_codes_values = self.parameterAsString(parameters, self.TYPE_CODES_VALUES, context).split(",")
        if not source_layer and not source_bbox:
            raise QgsProcessingException('There must be at least source layer or source bounding box.')
        if len(type_codes) != len(type_codes_values):
            raise QgsProcessingException('The type codes and its values do not match.')
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source_layer.fields(), source_layer.wkbType(), source_layer.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source_layer.featureCount() if source_layer.featureCount() else 0
        features = source_layer.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ims_preparer'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ims'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return IMSPreparerAlgorithm()
