# -*- coding: utf-8 -*-

"""
/***************************************************************************
 IMSPreparer
                                 A QGIS plugin
 This plugin prepares the IMS imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-14
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Leonid Kolesnichenko'
__date__ = '2024-02-14'
__copyright__ = '(C) 2024 by Leonid Kolesnichenko'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from PyQt5.QtCore import QVariant, QDateTime
from qgis import processing
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterString,
                       QgsProcessingParameterDateTime,
                       QgsProcessingParameterCrs,
                       QgsProcessingException,
                       QgsProcessingParameterDefinition,
                       QgsCoordinateReferenceSystem,
                       QgsRectangle,
                       QgsGeometry,
                       QgsFields,
                       QgsField,
                       QgsVectorLayer,
                       QgsFeature,
                       QgsRasterLayer,
                       QgsProject)


class IMSPreparerAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT_LAYER = 'INPUT_LAYER'
    INPUT_BBOX = 'INPUT_BBOX'
    RASTER_DATE = "RASTER_DATE"
    OUTPUT_CRS = "OUTPUT_CRS"
    TYPE_CODES = "TYPE_CODES"
    TYPE_CODES_VALUES = "TYPE_CODES_VALUES"

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.

        input_layer_param = QgsProcessingParameterFeatureSource(
            self.INPUT_LAYER,
            self.tr('Input layer'),
            [QgsProcessing.TypeVectorPolygon]
        )

        input_layer_param.setFlags(input_layer_param.flags() | QgsProcessingParameterDefinition.FlagOptional)

        self.addParameter(
            input_layer_param
        )

        bbox_param = QgsProcessingParameterString(
            self.INPUT_BBOX,
            self.tr('Bounding box (with comma separated)'),
            defaultValue=''
        )

        bbox_param.setFlags(bbox_param.flags() | QgsProcessingParameterDefinition.FlagOptional)

        self.addParameter(
            bbox_param
        )

        self.addParameter(
            QgsProcessingParameterDateTime(
                self.RASTER_DATE,
                self.tr('Raster date')
            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                self.OUTPUT_CRS,
                self.tr('Output CRS')
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.TYPE_CODES,
                self.tr('Type codes (comma separated)'),
                defaultValue=''
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.TYPE_CODES_VALUES,
                self.tr('Type codes values (comma separated)'),
                defaultValue=''
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source_layer = self.parameterAsSource(parameters, self.INPUT_LAYER, context)
        source_bbox = self.parameterAsString(parameters, self.INPUT_BBOX, context)
        target_crs = self.parameterAsCrs(parameters, self.OUTPUT_CRS, context)
        raster_date = self.parameterAsDateTime(parameters, self.RASTER_DATE, context)
        type_codes = self.parameterAsString(parameters, self.TYPE_CODES, context).split(",")
        type_codes_values = self.parameterAsString(parameters, self.TYPE_CODES_VALUES, context).split(",")

        output = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)

        raster_year, raster_month, raster_day = raster_date.date().year(), raster_date.date().month(), raster_date.date().day()
        raster_prd = f"66{str(raster_month).zfill(2)}{str(raster_day).zfill(2)}{raster_year}"
        raster_prd_uri = f"https://usicecenter.gov/File/DownloadArchive?prd={raster_prd}"
        today = QDateTime.currentDateTime()
        year_condition = raster_date.date().year() >= today.date().year()
        month_condition = raster_date.date().month() >= today.date().month()
        day_condition = raster_date.date().day() >= today.date().day()

        if all([year_condition, month_condition, day_condition]):
            raise QgsProcessingException('The raster date must be yesterday or earlier.')

        if not source_layer and not source_bbox:
            raise QgsProcessingException('There must be at least source layer or source bounding box.')
        if len(type_codes) != len(type_codes_values):
            raise QgsProcessingException('The type codes and its values do not match.')
        vector_layer = source_layer
        if source_bbox:
            xmin, ymin, xmax, ymax = map(float, source_bbox.split(','))
            bbox_rect = QgsRectangle(xmin, ymin, xmax, ymax)
            bbox_geometry = QgsGeometry.fromRect(bbox_rect)

            fields = QgsFields()
            fields.append(QgsField('ID', QVariant.Int))

            crs = QgsCoordinateReferenceSystem('EPSG:4326')
            vector_layer = QgsVectorLayer('Polygon?crs=' + crs.toWkt(), 'BoundingBox', 'memory')
            vector_layer_provider = vector_layer.dataProvider()
            vector_layer_provider.addAttributes(fields)
            vector_layer.updateFields()

            feature = QgsFeature()
            feature.setGeometry(bbox_geometry)
            feature.setAttributes([1])

            vector_layer_provider.addFeatures([feature])
            vector_layer.updateExtents()
            # TODO: get the geometry from bbox (gdal:cliprasterbymasklayer)

        file_downloader_params = {
            'DATA': '',
            'METHOD': 0,
            'URL': raster_prd_uri,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        file_downloader_results = processing.run("native:filedownloader", file_downloader_params)['OUTPUT']
        raster = QgsRasterLayer(f'/vsigzip/{file_downloader_results}', 'IMS Gzipped TIFF')

        clip_raster_params = {
            'INPUT': raster,
            'SOURCE_CRS': None,
            'MASK': vector_layer,
            'TARGET_CRS': QgsCoordinateReferenceSystem('EPSG:3857'),
            'RESAMPLING': 0,
            'NODATA': 0,
            'TARGET_RESOLUTION': 1000,
            'OPTIONS': '',
            'DATA_TYPE': 0,
            'TARGET_EXTENT': source_bbox if source_bbox else None,
            'TARGET_EXTENT_CRS': target_crs,
            'MULTITHREADING': True,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }
        clip_raster_result = processing.run("gdal:cliprasterbymasklayer", clip_raster_params)['OUTPUT']

        polygonize_params = {
            'INPUT': clip_raster_result,
            'BAND': 1,
            'OUTPUT': 'TEMPORARY_OUTPUT',
            'FIELD': 'TYPE_CODE'
        }

        polygonize_results = processing.run('gdal:polygonize', polygonize_params)['OUTPUT']

        extract_by_expression_params = {
            'INPUT': polygonize_results,
            'EXPRESSION': f'"TYPE_CODE"  IN ({",".join(type_codes)})',
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        extract_by_expression_results = processing.run('native:extractbyexpression', extract_by_expression_params)[
            'OUTPUT']

        dissolve_params = {
            'FIELD': 'TYPE_CODE',
            'INPUT': extract_by_expression_results,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        dissolve_results = processing.run('native:dissolve', dissolve_params)['OUTPUT']
        whens = []
        for idx, val in zip(type_codes, type_codes_values):
            whens.append(
                f"""WHEN "TYPE_CODE" = {idx} THEN '{val}'"""
            )
        whens = "\n".join(whens)

        field_calculator_typecode_params = {
            'INPUT': dissolve_results,
            'FIELD_NAME': 'TYPE',
            'FIELD_TYPE': 2,
            'FIELD_LENGTH': 10,
            'FIELD_PRECISION': 0,
            'FORMULA': f"""
            CASE
            {whens} 
            END
            """,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        field_calculator_typecode_results = processing.run('native:fieldcalculator', field_calculator_typecode_params)[
            'OUTPUT']

        field_calculator_date_params = {
            'INPUT': field_calculator_typecode_results,
            'FIELD_NAME': 'DATE',
            'FIELD_TYPE': 3,
            'FIELD_LENGTH': 10,
            'FIELD_PRECISION': 0,
            'FORMULA': f"'{str(raster_year)}-{str(raster_month).zfill(2)}-{str(raster_day).zfill(2)}'",
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        field_calculator_date_results = processing.run('native:fieldcalculator', field_calculator_date_params)['OUTPUT']

        fix_geometries_params = {
            'INPUT': field_calculator_date_results,
            'OUTPUT': output
        }

        fix_geometries_results = processing.run('native:fixgeometries', fix_geometries_params)['OUTPUT']


        return {self.OUTPUT: fix_geometries_results}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ims_preparer'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ims'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return IMSPreparerAlgorithm()
